# Generated by Django 5.2.1 on 2025-06-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='type',
            field=models.CharField(choices=[('Luxury', 'Luxury'), ('Premium', 'Premium'), ('Normal', 'Normal'), ('Adventure', 'Adventure'), ('Cultural', 'Cultural')], max_length=50),
        ),
    ]
