# Generated by Django 5.2.1 on 2025-06-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tourrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='admission_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tour',
            name='insurance_coverage',
            field=models.CharField(default='Not Covered', max_length=100),
        ),
        migrations.AddField(
            model_name='tour',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
    ]
