# Generated by Django 5.2.1 on 2025-07-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_tour_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='country_code',
            field=models.CharField(blank=True, help_text="ISO 3166-1 alpha-2 code e.g. 'NP'", max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, help_text="ISO country code, e.g. 'US'", max_length=2, null=True),
        ),
    ]
