# Generated by Django 5.2.1 on 2025-07-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_tour_country_code_user_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('cash', 'Cash')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='Max people (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='currency',
            field=models.CharField(default='USD', help_text='ISO 4217 currency code', max_length=3),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('partial_refunded', 'Partial Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'tour', 'booking_date')},
        ),
        migrations.AlterUniqueTogether(
            name='tour',
            unique_together={('title', 'city', 'country')},
        ),
    ]
